self.toolBar = QtGui.QToolBar()
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        self.actionSave_as = QtGui.QAction()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/save_as_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon1)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSave_as.setEnabled(False)
        self.actionClose = QtGui.QAction()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit_icon_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon3)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionZoom = QtGui.QAction()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/zoom_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon4)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionZoom.setEnabled(False)
        self.actionPan = QtGui.QAction()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/pan_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon5)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionPan.setEnabled(False)
        self.actionOrigin = QtGui.QAction()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/origin_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOrigin.setIcon(icon6)
        self.actionOrigin.setObjectName(_fromUtf8("actionOrigin"))
        self.actionOrigin.setEnabled(False)
        self.actionClear = QtGui.QAction()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/del_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon6)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionClear.setEnabled(False)
        self.actionSeparator1 = QtGui.QAction()
        self.actionSeparator1.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/separator_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSeparator1.setIcon(icon7)
        self.actionSeparator1.setObjectName(_fromUtf8("actionSeparator1"))
        self.actionSeparator2 = QtGui.QAction()
        self.actionSeparator2.setEnabled(False)
        self.actionSeparator2.setIcon(icon7)
        self.actionSeparator2.setObjectName(_fromUtf8("actionSeparator2"))
        self.actionSeparator3 = QtGui.QAction()
        self.actionSeparator3.setEnabled(False)
        self.actionSeparator3.setIcon(icon7)
        self.actionSeparator3.setObjectName(_fromUtf8("actionSeparator3"))
        self.toolBar.addAction(self.actionSave_as)
        self.toolBar.addAction(self.actionSeparator1)
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addAction(self.actionSeparator2)
        self.toolBar.addAction(self.actionOrigin)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actionSeparator3)
        self.toolBar.addAction(self.actionClose)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.pw_toolbar_fr.addWidget(self.toolBar)
        
        
        self.toolBar.setWindowTitle(_translate("plotWindow", "toolBar", None))
        self.actionSave_as.setText(_translate("plotWindow", "Save as...", None))
        self.actionSave_as.setToolTip(_translate("plotWindow", "Save to a graphic file", None))
        self.actionClose.setText(_translate("plotWindow", "Close...", None))
        self.actionClose.setToolTip(_translate("plotWindow", "Close the plot window", None))
        self.actionZoom.setText(_translate("plotWindow", "Zoom", None))
        self.actionZoom.setToolTip(_translate("plotWindow", "Zoom to rectangle", None))
        self.actionPan.setText(_translate("plotWindow", "Pan", None))
        self.actionPan.setToolTip(_translate("plotWindow", "Pan axes", None))
        self.actionOrigin.setText(_translate("plotWindow", "Origin", None))
        self.actionOrigin.setToolTip(_translate("plotWindow", "Reset to original view", None))
        self.actionClear.setText(_translate("plotWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("plotWindow", "Clear the view", None))