# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1112, 540)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/egads_icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow {\n"
"    background-color: rgb(240,240,240);\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuProcessings = QtGui.QMenu(self.menuBar)
        self.menuProcessings.setObjectName(_fromUtf8("menuProcessings"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpenBar = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/open_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenBar.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionOpenBar.setFont(font)
        self.actionOpenBar.setObjectName(_fromUtf8("actionOpenBar"))
        self.actionSaveBar = QtGui.QAction(MainWindow)
        self.actionSaveBar.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/save_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveBar.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionSaveBar.setFont(font)
        self.actionSaveBar.setObjectName(_fromUtf8("actionSaveBar"))
        self.actionCloseBar = QtGui.QAction(MainWindow)
        self.actionCloseBar.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCloseBar.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionCloseBar.setFont(font)
        self.actionCloseBar.setObjectName(_fromUtf8("actionCloseBar"))
        self.actionAlgorithmsBar = QtGui.QAction(MainWindow)
        self.actionAlgorithmsBar.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/new_algo_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlgorithmsBar.setIcon(icon4)
        self.actionAlgorithmsBar.setObjectName(_fromUtf8("actionAlgorithmsBar"))
        self.actionCreatealgorithmBar = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/create_algo_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreatealgorithmBar.setIcon(icon5)
        self.actionCreatealgorithmBar.setObjectName(_fromUtf8("actionCreatealgorithmBar"))
        self.actionCreateVariableBar = QtGui.QAction(MainWindow)
        self.actionCreateVariableBar.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/new_var_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateVariableBar.setIcon(icon6)
        self.actionCreateVariableBar.setObjectName(_fromUtf8("actionCreateVariableBar"))
        self.actionMigrateVariableBar = QtGui.QAction(MainWindow)
        self.actionMigrateVariableBar.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/migrate_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMigrateVariableBar.setIcon(icon7)
        self.actionMigrateVariableBar.setObjectName(_fromUtf8("actionMigrateVariableBar"))
        self.actionDeleteVariableBar = QtGui.QAction(MainWindow)
        self.actionDeleteVariableBar.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("icons/del_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteVariableBar.setIcon(icon8)
        self.actionDeleteVariableBar.setObjectName(_fromUtf8("actionDeleteVariableBar"))
        self.actionGlobalAttributesBar = QtGui.QAction(MainWindow)
        self.actionGlobalAttributesBar.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("icons/metadata_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGlobalAttributesBar.setIcon(icon9)
        self.actionGlobalAttributesBar.setObjectName(_fromUtf8("actionGlobalAttributesBar"))
        self.actionVariableAttributesBar = QtGui.QAction(MainWindow)
        self.actionVariableAttributesBar.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("icons/var_metadata_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVariableAttributesBar.setIcon(icon10)
        self.actionVariableAttributesBar.setObjectName(_fromUtf8("actionVariableAttributesBar"))
        self.actionPlotBar = QtGui.QAction(MainWindow)
        self.actionPlotBar.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("icons/plot_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlotBar.setIcon(icon11)
        self.actionPlotBar.setObjectName(_fromUtf8("actionPlotBar"))
        self.actionBatch_processing = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("icons/batch_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBatch_processing.setIcon(icon12)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionBatch_processing.setFont(font)
        self.actionBatch_processing.setObjectName(_fromUtf8("actionBatch_processing"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit_icon_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("icons/help_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon14)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout_EGADS = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("icons/about_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_EGADS.setIcon(icon15)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionAbout_EGADS.setFont(font)
        self.actionAbout_EGADS.setObjectName(_fromUtf8("actionAbout_EGADS"))
        self.actionChangelog = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("icons/changelog_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChangelog.setIcon(icon16)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionChangelog.setFont(font)
        self.actionChangelog.setObjectName(_fromUtf8("actionChangelog"))
        self.actionSeparator = QtGui.QAction(MainWindow)
        self.actionSeparator.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("icons/separator_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSeparator.setIcon(icon17)
        self.actionSeparator.setObjectName(_fromUtf8("actionSeparator"))
        self.actionSeparator2 = QtGui.QAction(MainWindow)
        self.actionSeparator2.setEnabled(False)
        self.actionSeparator2.setIcon(icon17)
        self.actionSeparator2.setVisible(True)
        self.actionSeparator2.setIconVisibleInMenu(True)
        self.actionSeparator2.setObjectName(_fromUtf8("actionSeparator2"))
        self.actionSeparator3 = QtGui.QAction(MainWindow)
        self.actionSeparator3.setEnabled(False)
        self.actionSeparator3.setIcon(icon17)
        self.actionSeparator3.setObjectName(_fromUtf8("actionSeparator3"))
        self.actionSeparator4 = QtGui.QAction(MainWindow)
        self.actionSeparator4.setEnabled(False)
        self.actionSeparator4.setIcon(icon17)
        self.actionSeparator4.setObjectName(_fromUtf8("actionSeparator4"))
        self.actionSaveAsBar = QtGui.QAction(MainWindow)
        self.actionSaveAsBar.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("icons/save_as_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAsBar.setIcon(icon18)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionSaveAsBar.setFont(font)
        self.actionSaveAsBar.setObjectName(_fromUtf8("actionSaveAsBar"))
        self.actionEmbedded_algorithms = QtGui.QAction(MainWindow)
        self.actionEmbedded_algorithms.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionEmbedded_algorithms.setFont(font)
        self.actionEmbedded_algorithms.setObjectName(_fromUtf8("actionEmbedded_algorithms"))
        self.actionUser_defined_algorithms = QtGui.QAction(MainWindow)
        self.actionUser_defined_algorithms.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Source Sans Pro"))
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.actionUser_defined_algorithms.setFont(font)
        self.actionUser_defined_algorithms.setObjectName(_fromUtf8("actionUser_defined_algorithms"))
        self.actionDisplayBar = QtGui.QAction(MainWindow)
        self.actionDisplayBar.setEnabled(False)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("icons/data_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisplayBar.setIcon(icon19)
        self.actionDisplayBar.setObjectName(_fromUtf8("actionDisplayBar"))
        self.menuFile.addAction(self.actionOpenBar)
        self.menuFile.addAction(self.actionSaveBar)
        self.menuFile.addAction(self.actionSaveAsBar)
        self.menuFile.addAction(self.actionCloseBar)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBatch_processing)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuProcessings.addAction(self.actionEmbedded_algorithms)
        self.menuProcessings.addAction(self.actionUser_defined_algorithms)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout_EGADS)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionChangelog)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuProcessings.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionOpenBar)
        self.toolBar.addAction(self.actionSaveBar)
        self.toolBar.addAction(self.actionSaveAsBar)
        self.toolBar.addAction(self.actionCloseBar)
        self.toolBar.addAction(self.actionSeparator)
        self.toolBar.addAction(self.actionAlgorithmsBar)
        self.toolBar.addAction(self.actionCreatealgorithmBar)
        self.toolBar.addAction(self.actionSeparator2)
        self.toolBar.addAction(self.actionCreateVariableBar)
        self.toolBar.addAction(self.actionMigrateVariableBar)
        self.toolBar.addAction(self.actionDeleteVariableBar)
        self.toolBar.addAction(self.actionSeparator3)
        self.toolBar.addAction(self.actionGlobalAttributesBar)
        self.toolBar.addAction(self.actionVariableAttributesBar)
        self.toolBar.addAction(self.actionSeparator4)
        self.toolBar.addAction(self.actionDisplayBar)
        self.toolBar.addAction(self.actionPlotBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "EGADS GUI", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuProcessings.setTitle(_translate("MainWindow", "Processings", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpenBar.setText(_translate("MainWindow", "Open...", None))
        self.actionOpenBar.setToolTip(_translate("MainWindow", "Open a file", None))
        self.actionSaveBar.setText(_translate("MainWindow", "Save...", None))
        self.actionSaveBar.setToolTip(_translate("MainWindow", "Save the current file", None))
        self.actionCloseBar.setText(_translate("MainWindow", "Close...", None))
        self.actionCloseBar.setToolTip(_translate("MainWindow", "Close the opened file", None))
        self.actionAlgorithmsBar.setText(_translate("MainWindow", "Algorithms", None))
        self.actionAlgorithmsBar.setToolTip(_translate("MainWindow", "Launch a process", None))
        self.actionCreatealgorithmBar.setText(_translate("MainWindow", "Create Algorithm", None))
        self.actionCreatealgorithmBar.setToolTip(_translate("MainWindow", "Create a new algorithm", None))
        self.actionCreateVariableBar.setText(_translate("MainWindow", "Create Variable", None))
        self.actionCreateVariableBar.setToolTip(_translate("MainWindow", "Create a new simple variable", None))
        self.actionMigrateVariableBar.setText(_translate("MainWindow", "Migrate Variable", None))
        self.actionMigrateVariableBar.setToolTip(_translate("MainWindow", "Migrate the selected variable to the main workspace", None))
        self.actionDeleteVariableBar.setText(_translate("MainWindow", "Delete Variable", None))
        self.actionDeleteVariableBar.setToolTip(_translate("MainWindow", "Delete the selected variable", None))
        self.actionGlobalAttributesBar.setText(_translate("MainWindow", "Global Attributes", None))
        self.actionGlobalAttributesBar.setToolTip(_translate("MainWindow", "Add or modify global attributes", None))
        self.actionVariableAttributesBar.setText(_translate("MainWindow", "Variable Attributes", None))
        self.actionVariableAttributesBar.setToolTip(_translate("MainWindow", "Add or modify the selected variable attributes", None))
        self.actionPlotBar.setText(_translate("MainWindow", "Plot", None))
        self.actionPlotBar.setToolTip(_translate("MainWindow", "Display a graph of the selected variable", None))
        self.actionBatch_processing.setText(_translate("MainWindow", "Batch processing...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit...", None))
        self.actionHelp.setText(_translate("MainWindow", "Help...", None))
        self.actionAbout_EGADS.setText(_translate("MainWindow", "About EGADS...", None))
        self.actionChangelog.setText(_translate("MainWindow", "Changelog...", None))
        self.actionSeparator.setText(_translate("MainWindow", "separator", None))
        self.actionSeparator2.setText(_translate("MainWindow", "separator2", None))
        self.actionSeparator3.setText(_translate("MainWindow", "separator3", None))
        self.actionSeparator4.setText(_translate("MainWindow", "separator4", None))
        self.actionSaveAsBar.setText(_translate("MainWindow", "Save as...", None))
        self.actionSaveAsBar.setToolTip(_translate("MainWindow", "Save in a new file", None))
        self.actionEmbedded_algorithms.setText(_translate("MainWindow", "Embedded algorithms", None))
        self.actionUser_defined_algorithms.setText(_translate("MainWindow", "User-defined algorithms", None))
        self.actionDisplayBar.setText(_translate("MainWindow", "Display", None))
        self.actionDisplayBar.setToolTip(_translate("MainWindow", "Display the selected variable", None))

