# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'global_attribute_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_globalAttributeWindow(object):
    def setupUi(self, globalAttributeWindow):
        globalAttributeWindow.setObjectName(_fromUtf8("globalAttributeWindow"))
        globalAttributeWindow.resize(700, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(globalAttributeWindow.sizePolicy().hasHeightForWidth())
        globalAttributeWindow.setSizePolicy(sizePolicy)
        globalAttributeWindow.setMinimumSize(QtCore.QSize(700, 400))
        globalAttributeWindow.setMaximumSize(QtCore.QSize(700, 400))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("fonts/SourceSansPro-Regular.ttf"))
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        globalAttributeWindow.setFont(font)
        self.gridLayout = QtGui.QGridLayout(globalAttributeWindow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gw_scrollArea = QtGui.QScrollArea(globalAttributeWindow)
        self.gw_scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.gw_scrollArea.setWidgetResizable(True)
        self.gw_scrollArea.setObjectName(_fromUtf8("gw_scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 665, 375))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gw_mandatoryAttributes_lb = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gw_mandatoryAttributes_lb.setMinimumSize(QtCore.QSize(250, 27))
        self.gw_mandatoryAttributes_lb.setMaximumSize(QtCore.QSize(250, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gw_mandatoryAttributes_lb.setFont(font)
        self.gw_mandatoryAttributes_lb.setObjectName(_fromUtf8("gw_mandatoryAttributes_lb"))
        self.horizontalLayout.addWidget(self.gw_mandatoryAttributes_lb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gw_conventions_lb = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gw_conventions_lb.setMinimumSize(QtCore.QSize(110, 27))
        self.gw_conventions_lb.setMaximumSize(QtCore.QSize(110, 27))
        self.gw_conventions_lb.setObjectName(_fromUtf8("gw_conventions_lb"))
        self.horizontalLayout_2.addWidget(self.gw_conventions_lb)
        self.gw_conventions_ln = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gw_conventions_ln.setEnabled(True)
        self.gw_conventions_ln.setMinimumSize(QtCore.QSize(400, 27))
        self.gw_conventions_ln.setMaximumSize(QtCore.QSize(400, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.gw_conventions_ln.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("fonts/SourceSansPro-Regular.ttf"))
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gw_conventions_ln.setFont(font)
        self.gw_conventions_ln.setStyleSheet(_fromUtf8("QLineEdit {border-radius: 3px; padding: 1px 4px 1px 4px; background-color: rgb(240, 240, 240);}\n"
"\n"
"QLineEdit:disabled {background-color: rgb(200,200,200);}"))
        self.gw_conventions_ln.setText(_fromUtf8(""))
        self.gw_conventions_ln.setFrame(False)
        self.gw_conventions_ln.setObjectName(_fromUtf8("gw_conventions_ln"))
        self.horizontalLayout_2.addWidget(self.gw_conventions_ln)
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gw_title_lb = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gw_title_lb.setMinimumSize(QtCore.QSize(110, 27))
        self.gw_title_lb.setMaximumSize(QtCore.QSize(110, 27))
        self.gw_title_lb.setObjectName(_fromUtf8("gw_title_lb"))
        self.horizontalLayout_3.addWidget(self.gw_title_lb)
        self.gw_title_ln = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gw_title_ln.setEnabled(True)
        self.gw_title_ln.setMinimumSize(QtCore.QSize(400, 27))
        self.gw_title_ln.setMaximumSize(QtCore.QSize(400, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.gw_title_ln.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("fonts/SourceSansPro-Regular.ttf"))
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gw_title_ln.setFont(font)
        self.gw_title_ln.setStyleSheet(_fromUtf8("QLineEdit {border-radius: 3px; padding: 1px 4px 1px 4px; background-color: rgb(240, 240, 240);}\n"
"\n"
"QLineEdit:disabled {background-color: rgb(200,200,200);}"))
        self.gw_title_ln.setText(_fromUtf8(""))
        self.gw_title_ln.setFrame(False)
        self.gw_title_ln.setObjectName(_fromUtf8("gw_title_ln"))
        self.horizontalLayout_3.addWidget(self.gw_title_ln)
        spacerItem4 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gw_institution_lb = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gw_institution_lb.setMinimumSize(QtCore.QSize(110, 27))
        self.gw_institution_lb.setMaximumSize(QtCore.QSize(110, 27))
        self.gw_institution_lb.setObjectName(_fromUtf8("gw_institution_lb"))
        self.horizontalLayout_4.addWidget(self.gw_institution_lb)
        self.gw_institution_ln = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gw_institution_ln.setEnabled(True)
        self.gw_institution_ln.setMinimumSize(QtCore.QSize(400, 27))
        self.gw_institution_ln.setMaximumSize(QtCore.QSize(400, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.gw_institution_ln.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("fonts/SourceSansPro-Regular.ttf"))
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gw_institution_ln.setFont(font)
        self.gw_institution_ln.setStyleSheet(_fromUtf8("QLineEdit {border-radius: 3px; padding: 1px 4px 1px 4px; background-color: rgb(240, 240, 240);}\n"
"\n"
"QLineEdit:disabled {background-color: rgb(200,200,200);}"))
        self.gw_institution_ln.setText(_fromUtf8(""))
        self.gw_institution_ln.setFrame(False)
        self.gw_institution_ln.setObjectName(_fromUtf8("gw_institution_ln"))
        self.horizontalLayout_4.addWidget(self.gw_institution_ln)
        spacerItem6 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.gw_source_lb = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gw_source_lb.setMinimumSize(QtCore.QSize(110, 27))
        self.gw_source_lb.setMaximumSize(QtCore.QSize(110, 27))
        self.gw_source_lb.setObjectName(_fromUtf8("gw_source_lb"))
        self.horizontalLayout_5.addWidget(self.gw_source_lb)
        self.gw_source_ln = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.gw_source_ln.setEnabled(True)
        self.gw_source_ln.setMinimumSize(QtCore.QSize(400, 27))
        self.gw_source_ln.setMaximumSize(QtCore.QSize(400, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.gw_source_ln.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("fonts/SourceSansPro-Regular.ttf"))
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gw_source_ln.setFont(font)
        self.gw_source_ln.setStyleSheet(_fromUtf8("QLineEdit {border-radius: 3px; padding: 1px 4px 1px 4px; background-color: rgb(240, 240, 240);}\n"
"\n"
"QLineEdit:disabled {background-color: rgb(200,200,200);}"))
        self.gw_source_ln.setText(_fromUtf8(""))
        self.gw_source_ln.setFrame(False)
        self.gw_source_ln.setObjectName(_fromUtf8("gw_source_ln"))
        self.horizontalLayout_5.addWidget(self.gw_source_ln)
        spacerItem8 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem9)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        spacerItem10 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gw_showButton = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.gw_showButton.setMinimumSize(QtCore.QSize(180, 27))
        self.gw_showButton.setMaximumSize(QtCore.QSize(180, 27))
        self.gw_showButton.setObjectName(_fromUtf8("gw_showButton"))
        self.horizontalLayout_8.addWidget(self.gw_showButton)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.vl_otherAttribute = QtGui.QVBoxLayout()
        self.vl_otherAttribute.setSpacing(6)
        self.vl_otherAttribute.setObjectName(_fromUtf8("vl_otherAttribute"))
        self.verticalLayout.addLayout(self.vl_otherAttribute)
        spacerItem12 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem12)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem13 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gw_addAttribute_lb = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.gw_addAttribute_lb.setMinimumSize(QtCore.QSize(130, 27))
        self.gw_addAttribute_lb.setMaximumSize(QtCore.QSize(130, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gw_addAttribute_lb.setFont(font)
        self.gw_addAttribute_lb.setObjectName(_fromUtf8("gw_addAttribute_lb"))
        self.horizontalLayout_6.addWidget(self.gw_addAttribute_lb)
        self.gw_addAttribute_rl = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.gw_addAttribute_rl.setMinimumSize(QtCore.QSize(300, 27))
        self.gw_addAttribute_rl.setMaximumSize(QtCore.QSize(300, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("fonts/SourceSansPro-Regular.ttf"))
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gw_addAttribute_rl.setFont(font)
        self.gw_addAttribute_rl.setStyleSheet(_fromUtf8("QComboBox {border-radius: 3px; padding: 1px 4px 1px 4px; background-color: rgb(240, 240, 240);}\n"
"\n"
"QComboBox::drop-down {subcontrol-origin: padding; subcontrol-position: top right; width: 27px; border-top-right-radius: 3px; border-bottom-right-radius: 3px;}\n"
"\n"
"QComboBox::drop-down:hover {subcontrol-origin: padding; subcontrol-position: top right; width: 27px; border-left-width: 1px; border-left-color: darkgray; border-left-style: solid; border-top-right-radius: 3px; border-bottom-right-radius: 3px;}\n"
"\n"
"QComboBox::down-arrow {image: url(images/arrow_down.png); width: 18px; height: 18px;}\n"
"\n"
"QComboBox::down-arrow:on {top: 1px; left: 1px;}\n"
"\n"
"QComboBox QAbstractItemView {background-color: rgb(240,240,240); selection-color: blue; padding: 4px 1px 4px 1px;}"))
        self.gw_addAttribute_rl.setObjectName(_fromUtf8("gw_addAttribute_rl"))
        self.horizontalLayout_6.addWidget(self.gw_addAttribute_rl)
        self.gw_button_1 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.gw_button_1.setMinimumSize(QtCore.QSize(27, 27))
        self.gw_button_1.setMaximumSize(QtCore.QSize(27, 27))
        self.gw_button_1.setStyleSheet(_fromUtf8("QToolButton:hover {border: 1px solid gray; border-radius: 3px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde); width: 27px; height: 27px;}\n"
"\n"
"QToolButton:pressed {background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"\n"
"QToolButton:flat {border: none;}"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/plus_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gw_button_1.setIcon(icon)
        self.gw_button_1.setIconSize(QtCore.QSize(27, 27))
        self.gw_button_1.setAutoRaise(True)
        self.gw_button_1.setObjectName(_fromUtf8("gw_button_1"))
        self.horizontalLayout_6.addWidget(self.gw_button_1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem15 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.vl_addAttribute = QtGui.QVBoxLayout()
        self.vl_addAttribute.setObjectName(_fromUtf8("vl_addAttribute"))
        self.verticalLayout.addLayout(self.vl_addAttribute)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gw_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.gw_scrollArea)
        spacerItem16 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem16)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem17 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.gw_cancelButton = QtGui.QToolButton(globalAttributeWindow)
        self.gw_cancelButton.setMinimumSize(QtCore.QSize(100, 27))
        self.gw_cancelButton.setMaximumSize(QtCore.QSize(100, 27))
        self.gw_cancelButton.setObjectName(_fromUtf8("gw_cancelButton"))
        self.horizontalLayout_7.addWidget(self.gw_cancelButton)
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.gw_okButton = QtGui.QToolButton(globalAttributeWindow)
        self.gw_okButton.setMinimumSize(QtCore.QSize(100, 27))
        self.gw_okButton.setMaximumSize(QtCore.QSize(100, 27))
        self.gw_okButton.setObjectName(_fromUtf8("gw_okButton"))
        self.horizontalLayout_7.addWidget(self.gw_okButton)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(globalAttributeWindow)
        QtCore.QMetaObject.connectSlotsByName(globalAttributeWindow)

    def retranslateUi(self, globalAttributeWindow):
        globalAttributeWindow.setWindowTitle(_translate("globalAttributeWindow", "Global Attributes", None))
        self.gw_mandatoryAttributes_lb.setText(_translate("globalAttributeWindow", "Mandatory global attributes", None))
        self.gw_conventions_lb.setText(_translate("globalAttributeWindow", "Conventions:", None))
        self.gw_title_lb.setText(_translate("globalAttributeWindow", "title:", None))
        self.gw_institution_lb.setText(_translate("globalAttributeWindow", "institution:", None))
        self.gw_source_lb.setText(_translate("globalAttributeWindow", "source:", None))
        self.gw_showButton.setText(_translate("globalAttributeWindow", "Show other attributes", None))
        self.gw_addAttribute_lb.setText(_translate("globalAttributeWindow", "Add attribute:", None))
        self.gw_button_1.setText(_translate("globalAttributeWindow", "...", None))
        self.gw_cancelButton.setText(_translate("globalAttributeWindow", "Cancel", None))
        self.gw_okButton.setText(_translate("globalAttributeWindow", "Save", None))

