import logging
from PyQt5 import QtWidgets, QtCore
from egads import EgadsData
from functions.utils import (font_creation_function, icon_creation_function, stylesheet_creation_function,
                             full_path_name_from_treewidget, clear_layout)
from functions.gui_functions.gui_widgets import PushButtonRight, MyTreeWidget
from functions.gui_functions.gui_global_functions import (update_icons_state, modify_attribute_gui_var,
                                                          update_edit_icon_state, read_set_attribute_gui,
                                                          populate_tree_widget)


def add_new_variable_tab(self):
    self.tab_view.insertTab(2, self.tab_3, 'New variables')
    font1 = font_creation_function('normal')
    self.new_splitter = QtWidgets.QSplitter()
    self.new_splitter.setStyleSheet(stylesheet_creation_function('qsplitter'))
    self.new_splitter.setOrientation(QtCore.Qt.Horizontal)
    self.new_splitter.setObjectName("new_splitter")
    self.new_variable_list = MyTreeWidget(self.new_splitter)
    self.new_variable_list.setEnabled(True)
    self.new_variable_list.setMinimumSize(QtCore.QSize(0, 0))
    self.new_variable_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.new_variable_list.setFont(font1)
    self.new_variable_list.setFocusPolicy(QtCore.Qt.NoFocus)
    self.new_variable_list.setStyleSheet(stylesheet_creation_function('qtreewidget'))
    self.new_variable_list.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.new_variable_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
    self.new_variable_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
    self.new_variable_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)

    self.new_variable_list.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
    self.new_variable_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)

    # self.new_variable_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
    # self.new_variable_list.setDefaultDropAction(QtCore.Qt.MoveAction)
    self.new_variable_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
    self.new_variable_list.setObjectName("new_variable_list")
    self.new_variable_list.headerItem().setText(0, "1")
    self.new_variable_list.header().setVisible(False)
    self.new_variable_widget = QtWidgets.QWidget(self.new_splitter)
    self.new_variable_widget.setObjectName("new_variable_widget")
    self.new_metadata_container = QtWidgets.QVBoxLayout(self.new_variable_widget)
    self.new_metadata_container.setContentsMargins(0, 0, 0, 0)
    self.new_metadata_container.setObjectName("new_metadata_container")
    self.newvariable_widget_container.addWidget(self.new_splitter)
    self.new_splitter.setSizes([270, 582])
    self.new_variable_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
    self.new_variable_list.customContextMenuRequested.connect(self.right_click_menu)
    self.new_variable_list.itemClicked.connect(lambda: new_tree_var_reading(self))
    self.new_variable_list.itemClicked.connect(lambda: update_icons_state(self))
    self.new_variable_list.dropFile.connect(lambda path_object: move_object_in_variable_dict(self, path_object))


def new_tree_var_reading(self):
    if len(self.new_variable_list.selectedItems()) == 1:
        path, _ = full_path_name_from_treewidget(self.new_variable_list)
        try:
            var_object = self.list_of_new_variables_and_attributes[path]
        except KeyError:
            var_object = self.list_of_new_variables_and_attributes[path[1:]]
        clear_layout(self.new_metadata_container)
        if isinstance(var_object[0], EgadsData):
            add_new_variable_metadata_widgets(self)
        else:
            add_new_group_metadata_widgets(self)
        update_new_variable_attribute_gui(self)
        update_edit_icon_state(self)
    else:
        clear_layout(self.new_metadata_container)


def add_new_variable_metadata_widgets(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    self.new_dataset_grid = QtWidgets.QGridLayout()
    self.new_dataset_grid.setContentsMargins(5, -1, -1, -1)
    self.new_dataset_grid.setVerticalSpacing(10)
    self.new_dataset_grid.setObjectName("new_dataset_grid")
    self.new_varname_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_varname_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_varname_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_varname_lb.setFont(font1)
    self.new_varname_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_varname_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_varname_lb.setObjectName("new_varname_lb")
    self.new_dataset_grid.addWidget(self.new_varname_lb, 1, 0, 1, 1)
    self.new_long_name_bt = PushButtonRight(self.new_variable_widget)
    self.new_long_name_bt.setEnabled(False)
    self.new_long_name_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.new_long_name_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.new_long_name_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.new_long_name_bt.setText("")
    self.new_long_name_bt.setIcon(icon1)
    self.new_long_name_bt.setIconSize(QtCore.QSize(23, 23))
    self.new_long_name_bt.setObjectName("new_long_name_bt")
    self.new_dataset_grid.addWidget(self.new_long_name_bt, 2, 2, 1, 1)
    self.new_dimensions_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_dimensions_ln.setEnabled(False)
    self.new_dimensions_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_dimensions_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_dimensions_ln.setFont(font2)
    self.new_dimensions_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_dimensions_ln.setText("")
    self.new_dimensions_ln.setFrame(False)
    self.new_dimensions_ln.setObjectName("var_dimensions_ln")
    self.new_dataset_grid.addWidget(self.new_dimensions_ln, 6, 1, 1, 1)
    self.new_long_name_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_long_name_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_long_name_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_long_name_lb.setFont(font1)
    self.new_long_name_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_long_name_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_long_name_lb.setObjectName("new_long_name_lb")
    self.new_dataset_grid.addWidget(self.new_long_name_lb, 2, 0, 1, 1)
    self.new_long_name_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_long_name_ln.setEnabled(False)
    self.new_long_name_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_long_name_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_long_name_ln.setFont(font2)
    self.new_long_name_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_long_name_ln.setText("")
    self.new_long_name_ln.setFrame(False)
    self.new_long_name_ln.setObjectName("new_long_name_ln")
    self.new_dataset_grid.addWidget(self.new_long_name_ln, 2, 1, 1, 1)
    self.new_fillvalue_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_fillvalue_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_fillvalue_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_fillvalue_lb.setFont(font1)
    self.new_fillvalue_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_fillvalue_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_fillvalue_lb.setObjectName("new_fillvalue_lb")
    self.new_dataset_grid.addWidget(self.new_fillvalue_lb, 5, 0, 1, 1)
    self.new_units_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_units_ln.setEnabled(False)
    self.new_units_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_units_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_units_ln.setFont(font2)
    self.new_units_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_units_ln.setText("")
    self.new_units_ln.setFrame(False)
    self.new_units_ln.setObjectName("new_units_ln")
    self.new_dataset_grid.addWidget(self.new_units_ln, 4, 1, 1, 1)
    self.new_egadsprocessor_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_egadsprocessor_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_egadsprocessor_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.new_egadsprocessor_lb.setFont(font1)
    self.new_egadsprocessor_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_egadsprocessor_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
    self.new_egadsprocessor_lb.setObjectName("new_egadsprocessor_lb")
    self.new_dataset_grid.addWidget(self.new_egadsprocessor_lb, 7, 0, 1, 1)
    self.new_varname_bt = PushButtonRight(self.new_variable_widget)
    self.new_varname_bt.setEnabled(False)
    self.new_varname_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.new_varname_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.new_varname_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.new_varname_bt.setText("")
    self.new_varname_bt.setIcon(icon1)
    self.new_varname_bt.setIconSize(QtCore.QSize(23, 23))
    self.new_varname_bt.setObjectName("new_varname_bt")
    self.new_dataset_grid.addWidget(self.new_varname_bt, 1, 2, 1, 1)
    self.new_Category_bt = PushButtonRight(self.new_variable_widget)
    self.new_Category_bt.setEnabled(False)
    self.new_Category_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.new_Category_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.new_Category_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.new_Category_bt.setText("")
    self.new_Category_bt.setIcon(icon1)
    self.new_Category_bt.setIconSize(QtCore.QSize(23, 23))
    self.new_Category_bt.setObjectName("new_Category_bt")
    self.new_dataset_grid.addWidget(self.new_Category_bt, 3, 2, 1, 1)
    self.new_dimensions_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_dimensions_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_dimensions_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_dimensions_lb.setFont(font1)
    self.new_dimensions_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_dimensions_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_dimensions_lb.setObjectName("new_dimensions_lb")
    self.new_dataset_grid.addWidget(self.new_dimensions_lb, 6, 0, 1, 1)
    self.new_varname_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_varname_ln.setEnabled(False)
    self.new_varname_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_varname_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_varname_ln.setFont(font2)
    self.new_varname_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_varname_ln.setText("")
    self.new_varname_ln.setFrame(False)
    self.new_varname_ln.setObjectName("new_varname_ln")
    self.new_dataset_grid.addWidget(self.new_varname_ln, 1, 1, 1, 1)
    self.new_Category_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_Category_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_Category_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_Category_lb.setFont(font1)
    self.new_Category_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_Category_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_Category_lb.setObjectName("new_Category_lb")
    self.new_dataset_grid.addWidget(self.new_Category_lb, 3, 0, 1, 1)
    self.new_egadsprocessor_ln = QtWidgets.QPlainTextEdit(self.new_variable_widget)
    self.new_egadsprocessor_ln.setEnabled(False)
    self.new_egadsprocessor_ln.setMinimumSize(QtCore.QSize(0, 50))
    self.new_egadsprocessor_ln.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.new_egadsprocessor_ln.setFont(font2)
    self.new_egadsprocessor_ln.setStyleSheet(stylesheet_creation_function('qplaintextedit'))
    self.new_egadsprocessor_ln.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.new_egadsprocessor_ln.setPlainText("")
    self.new_egadsprocessor_ln.setObjectName("new_egadsprocessor_ln")
    self.new_dataset_grid.addWidget(self.new_egadsprocessor_ln, 7, 1, 1, 1)
    self.new_fillvalue_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_fillvalue_ln.setEnabled(False)
    self.new_fillvalue_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_fillvalue_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_fillvalue_ln.setFont(font2)
    self.new_fillvalue_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_fillvalue_ln.setText("")
    self.new_fillvalue_ln.setFrame(False)
    self.new_fillvalue_ln.setObjectName("new_fillvalue_ln")
    self.new_dataset_grid.addWidget(self.new_fillvalue_ln, 5, 1, 1, 1)
    self.new_Category_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_Category_ln.setEnabled(False)
    self.new_Category_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_Category_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_Category_ln.setFont(font2)
    self.new_Category_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_Category_ln.setText("")
    self.new_Category_ln.setFrame(False)
    self.new_Category_ln.setObjectName("new_Category_ln")
    self.new_dataset_grid.addWidget(self.new_Category_ln, 3, 1, 1, 1)
    self.new_units_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_units_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_units_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_units_lb.setFont(font1)
    self.new_units_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_units_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_units_lb.setObjectName("new_units_lb")
    self.new_dataset_grid.addWidget(self.new_units_lb, 4, 0, 1, 1)
    self.new_objecttype_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_objecttype_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_objecttype_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_objecttype_lb.setFont(font1)
    self.new_objecttype_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_objecttype_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_objecttype_lb.setObjectName("new_objecttype_lb")
    self.new_dataset_grid.addWidget(self.new_objecttype_lb, 0, 0, 1, 1)
    self.new_objecttype_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_objecttype_ln.setEnabled(False)
    self.new_objecttype_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_objecttype_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_objecttype_ln.setFont(font2)
    self.new_objecttype_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_objecttype_ln.setText("")
    self.new_objecttype_ln.setFrame(False)
    self.new_objecttype_ln.setObjectName("new_objecttype_ln")
    self.new_dataset_grid.addWidget(self.new_objecttype_ln, 0, 1, 1, 1)
    self.new_metadata_container.addLayout(self.new_dataset_grid)
    self.new_metadata_container.setAlignment(QtCore.Qt.AlignTop)
    self.new_varname_lb.setText("Variable name:")
    self.new_long_name_lb.setText("Long name:")
    self.new_fillvalue_lb.setText("Fill value:")
    self.new_egadsprocessor_lb.setText("<html><head/><body><p>EGADS<br/>processors:</p></body></html>")
    self.new_dimensions_lb.setText("Dimensions:")
    self.new_Category_lb.setText("Category:")
    self.new_units_lb.setText("Units:")
    self.new_objecttype_lb.setText("Object type:")
    var_buttons = self.new_variable_widget.findChildren(PushButtonRight)
    for widget in var_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_var(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_var(self, 'right'))


def add_new_group_metadata_widgets(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    self.new_group_grid = QtWidgets.QGridLayout()
    self.new_group_grid.setContentsMargins(5, -1, -1, -1)
    self.new_group_grid.setVerticalSpacing(10)
    self.new_group_grid.setObjectName("new_group_grid")
    self.new_objecttype_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_objecttype_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_objecttype_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_objecttype_lb.setFont(font1)
    self.new_objecttype_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_objecttype_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_objecttype_lb.setObjectName("new_objecttype_lb")
    self.new_group_grid.addWidget(self.new_objecttype_lb, 0, 0, 1, 1)
    self.new_groupname_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_groupname_ln.setEnabled(False)
    self.new_groupname_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_groupname_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_groupname_ln.setFont(font2)
    self.new_groupname_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_groupname_ln.setText("")
    self.new_groupname_ln.setFrame(False)
    self.new_groupname_ln.setObjectName("new_groupname_ln")
    self.new_group_grid.addWidget(self.new_groupname_ln, 1, 1, 1, 1)
    self.new_objecttype_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_objecttype_ln.setEnabled(False)
    self.new_objecttype_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_objecttype_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_objecttype_ln.setFont(font2)
    self.new_objecttype_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_objecttype_ln.setText("")
    self.new_objecttype_ln.setFrame(False)
    self.new_objecttype_ln.setObjectName("new_objecttype_ln")
    self.new_group_grid.addWidget(self.new_objecttype_ln, 0, 1, 1, 1)
    self.new_groupname_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_groupname_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_groupname_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_groupname_lb.setFont(font1)
    self.new_groupname_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_groupname_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_groupname_lb.setObjectName("new_groupname_lb")
    self.new_group_grid.addWidget(self.new_groupname_lb, 1, 0, 1, 1)
    self.new_groupdimension_ln = QtWidgets.QLineEdit(self.new_variable_widget)
    self.new_groupdimension_ln.setEnabled(False)
    self.new_groupdimension_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.new_groupdimension_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_groupdimension_ln.setFont(font2)
    self.new_groupdimension_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.new_groupdimension_ln.setText("")
    self.new_groupdimension_ln.setFrame(False)
    self.new_groupdimension_ln.setObjectName("var_groupdimension_ln")
    self.new_group_grid.addWidget(self.new_groupdimension_ln, 2, 1, 1, 1)
    self.new_groupname_bt = PushButtonRight(self.new_variable_widget)
    self.new_groupname_bt.setEnabled(False)
    self.new_groupname_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.new_groupname_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.new_groupname_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.new_groupname_bt.setText("")
    self.new_groupname_bt.setIcon(icon1)
    self.new_groupname_bt.setIconSize(QtCore.QSize(23, 23))
    self.new_groupname_bt.setObjectName("new_groupname_bt")
    self.new_group_grid.addWidget(self.new_groupname_bt, 1, 2, 1, 1)
    self.new_groupdimension_lb = QtWidgets.QLabel(self.new_variable_widget)
    self.new_groupdimension_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.new_groupdimension_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.new_groupdimension_lb.setFont(font1)
    self.new_groupdimension_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.new_groupdimension_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.new_groupdimension_lb.setObjectName("new_groupdimension_lb")
    self.new_group_grid.addWidget(self.new_groupdimension_lb, 2, 0, 1, 1)
    self.new_metadata_container.addLayout(self.new_group_grid)
    self.new_metadata_container.setAlignment(QtCore.Qt.AlignTop)
    self.new_objecttype_lb.setText("Object type:")
    self.new_groupname_lb.setText("Group name:")
    self.new_groupdimension_lb.setText("Dimensions:")
    var_buttons = self.new_variable_widget.findChildren(PushButtonRight)
    for widget in var_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_var(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_var(self, 'right'))


def populate_newvariable_tree_widget(self):
    populate_tree_widget(self.new_variable_list, self.list_of_new_variables_and_attributes)


def update_new_variable_attribute_gui(self):
    logging.debug('gui - gui_netcdf_functions.py - update_nc_variable_attribute_gui')
    path, var = full_path_name_from_treewidget(self.new_variable_list)
    try:
        sublist = self.list_of_new_variables_and_attributes[path]
    except KeyError:
        sublist = self.list_of_new_variables_and_attributes[path[1:]]
    dimensions_str = ''
    if isinstance(sublist[0], EgadsData):
        read_set_attribute_gui(self.new_objecttype_ln, 'Dataset')
        read_set_attribute_gui(self.new_varname_ln, var)
        read_set_attribute_gui(self.new_long_name_ln, 'long_name', sublist[0].metadata)
        read_set_attribute_gui(self.new_units_ln, 'units', sublist[0].metadata)
        read_set_attribute_gui(self.new_Category_ln, 'Category', sublist[0].metadata)
        read_set_attribute_gui(self.new_egadsprocessor_ln, 'Processor', sublist[0].metadata)
        read_set_attribute_gui(self.new_fillvalue_ln, '_FillValue', sublist[0].metadata)
        if not self.new_fillvalue_ln.text():
            read_set_attribute_gui(self.new_fillvalue_ln, 'missing_value', sublist[0].metadata)
        for key, value in sublist[1].items():
            dimensions_str = dimensions_str + str(value) + ' (' + key + '), '
        read_set_attribute_gui(self.new_dimensions_ln, dimensions_str[:-2])
    else:
        read_set_attribute_gui(self.new_objecttype_ln, 'Group')
        read_set_attribute_gui(self.new_groupname_ln, var)
        if sublist[2]:
            for key, value in sublist[2].items():
                dimensions_str = dimensions_str + str(value) + ' (' + key + '), '
            read_set_attribute_gui(self.new_groupdimension_ln, dimensions_str[:-2])
