import logging
import os
from egads import EgadsData
from PyQt5 import QtWidgets, QtCore
from functions.utils import (font_creation_function, clear_layout, icon_creation_function, stylesheet_creation_function,
                             full_path_name_from_treewidget)
from functions.gui_functions.gui_widgets import PushButtonRight, MyTreeWidget
from functions.gui_functions.gui_global_functions import (read_set_attribute_gui, modify_attribute_gui_global,
                                                          modify_attribute_gui_var, update_icons_state,
                                                          update_edit_icon_state, populate_tree_widget,
                                                          update_tree_widget)
from functions.gui_functions.gui_support_functions import move_object_in_variable_dict
from functions.window_functions.other_windows_functions import MyDimensionSelection


def netcdf_gui_initialization(self):
    logging.debug('gui - old_gui_global_functions.py - netcdf_gui_initialization')
    self.gridLayout.addWidget(self.tab_view, 0, 0, 1, 1)
    self.tab_view.setEnabled(True)
    self.tab_view.setVisible(True)
    self.tab_view.currentChanged.connect(lambda: update_icons_state(self))
    add_netcdf_global_tab(self)
    add_netcdf_variable_tab(self)


def nc_tree_var_reading(self):
    if len(self.variable_list.selectedItems()) == 1:
        path, _ = full_path_name_from_treewidget(self.variable_list)

        try:
            var_object = self.list_of_variables_and_attributes[path]
        except KeyError:
            var_object = self.list_of_variables_and_attributes[path[1:]]
        clear_layout(self.metadata_container)
        if isinstance(var_object[0], EgadsData):
            add_netcdf_variable_metadata_widgets(self)
        else:
            add_netcdf_group_metadata_widgets(self)
        update_nc_variable_attribute_gui(self)
        update_edit_icon_state(self)
    else:
        clear_layout(self.metadata_container)


def add_netcdf_global_tab(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    self.global_widget = QtWidgets.QWidget()
    self.global_widget.setObjectName("global_widget")
    self.global_grid = QtWidgets.QGridLayout()
    self.global_grid.setVerticalSpacing(15)
    self.global_grid.setObjectName("global_grid")
    self.glo_source_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_source_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_source_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_source_lb.setFont(font1)
    self.glo_source_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_source_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_source_lb.setObjectName("glo_source_lb")
    self.global_grid.addWidget(self.glo_source_lb, 0, 4, 1, 1)
    self.glo_project_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_project_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_project_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_project_lb.setFont(font1)
    self.glo_project_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_project_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_project_lb.setObjectName("glo_project_lb")
    self.global_grid.addWidget(self.glo_project_lb, 1, 4, 1, 1)
    self.glo_title_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_title_ln.setEnabled(False)
    self.glo_title_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_title_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_title_ln.setFont(font2)
    self.glo_title_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_title_ln.setText("")
    self.glo_title_ln.setFrame(False)
    self.glo_title_ln.setObjectName("glo_title_ln")
    self.global_grid.addWidget(self.glo_title_ln, 0, 1, 1, 1)
    self.glo_source_bt = PushButtonRight(self.global_widget)
    self.glo_source_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_source_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_source_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_source_bt.setText("")
    self.glo_source_bt.setIcon(icon1)
    self.glo_source_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_source_bt.setObjectName("glo_source_bt")
    self.global_grid.addWidget(self.glo_source_bt, 0, 6, 1, 1)
    self.glo_source_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_source_ln.setEnabled(False)
    self.glo_source_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_source_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_source_ln.setFont(font2)
    self.glo_source_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_source_ln.setText("")
    self.glo_source_ln.setFrame(False)
    self.glo_source_ln.setObjectName("glo_source_ln")
    self.global_grid.addWidget(self.glo_source_ln, 0, 5, 1, 1)
    self.glo_project_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_project_ln.setEnabled(False)
    self.glo_project_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_project_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_project_ln.setFont(font2)
    self.glo_project_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_project_ln.setText("")
    self.glo_project_ln.setFrame(False)
    self.glo_project_ln.setObjectName("glo_project_ln")
    self.global_grid.addWidget(self.glo_project_ln, 1, 5, 1, 1)
    self.glo_history_ln = QtWidgets.QPlainTextEdit(self.global_widget)
    self.glo_history_ln.setEnabled(False)
    self.glo_history_ln.setMinimumSize(QtCore.QSize(0, 50))
    self.glo_history_ln.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.glo_history_ln.setFont(font2)
    self.glo_history_ln.setStyleSheet(stylesheet_creation_function('qplaintextedit'))
    self.glo_history_ln.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.glo_history_ln.setPlainText("")
    self.glo_history_ln.setObjectName("glo_history_ln")
    self.global_grid.addWidget(self.glo_history_ln, 2, 1, 1, 5)
    self.glo_institution_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_institution_ln.setEnabled(False)
    self.glo_institution_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_institution_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_institution_ln.setFont(font2)
    self.glo_institution_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_institution_ln.setText("")
    self.glo_institution_ln.setFrame(False)
    self.glo_institution_ln.setObjectName("glo_institution_ln")
    self.global_grid.addWidget(self.glo_institution_ln, 1, 1, 1, 1)
    self.glo_title_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_title_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_title_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_title_lb.setFont(font1)
    self.glo_title_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_title_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_title_lb.setObjectName("glo_title_lb")
    self.global_grid.addWidget(self.glo_title_lb, 0, 0, 1, 1)
    self.glo_institution_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_institution_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_institution_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_institution_lb.setFont(font1)
    self.glo_institution_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_institution_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_institution_lb.setObjectName("glo_institution_lb")
    self.global_grid.addWidget(self.glo_institution_lb, 1, 0, 1, 1)
    self.glo_project_bt = PushButtonRight(self.global_widget)
    self.glo_project_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_project_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_project_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_project_bt.setText("")
    self.glo_project_bt.setIcon(icon1)
    self.glo_project_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_project_bt.setObjectName("glo_project_bt")
    self.global_grid.addWidget(self.glo_project_bt, 1, 6, 1, 1)
    self.glo_title_bt = PushButtonRight(self.global_widget)
    self.glo_title_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_title_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_title_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_title_bt.setText("")
    self.glo_title_bt.setIcon(icon1)
    self.glo_title_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_title_bt.setObjectName("glo_title_bt")
    self.global_grid.addWidget(self.glo_title_bt, 0, 2, 1, 1)
    self.global_grid.addItem(QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed,
                                                   QtWidgets.QSizePolicy.Minimum), 0, 3, 2, 1)
    self.glo_institution_bt = PushButtonRight(self.global_widget)
    self.glo_institution_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_institution_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_institution_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_institution_bt.setText("")
    self.glo_institution_bt.setIcon(icon1)
    self.glo_institution_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_institution_bt.setObjectName("glo_institution_bt")
    self.global_grid.addWidget(self.glo_institution_bt, 1, 2, 1, 1)
    self.glo_history_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_history_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_history_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.glo_history_lb.setFont(font1)
    self.glo_history_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_history_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
    self.glo_history_lb.setObjectName("glo_history_lb")
    self.global_grid.addWidget(self.glo_history_lb, 2, 0, 1, 1)
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.glo_history_bt = PushButtonRight(self.global_widget)
    self.glo_history_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_history_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_history_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_history_bt.setText("")
    self.glo_history_bt.setIcon(icon1)
    self.glo_history_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_history_bt.setObjectName("glo_history_bt")
    self.verticalLayout.addWidget(self.glo_history_bt)
    self.verticalLayout.addItem(QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                      QtWidgets.QSizePolicy.Expanding))
    self.global_grid.addLayout(self.verticalLayout, 2, 6, 1, 1)
    self.global_container.addLayout(self.global_grid)
    self.global_container.setAlignment(QtCore.Qt.AlignTop)
    self.glo_source_lb.setText("Source:")
    self.glo_project_lb.setText("Project:")
    self.glo_title_lb.setText("Title:")
    self.glo_institution_lb.setText("Institution:")
    self.glo_history_lb.setText("History:")
    glo_buttons = self.tab.findChildren(PushButtonRight)
    for widget in glo_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_global(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_global(self, 'right'))


def add_netcdf_variable_tab(self):
    font1 = font_creation_function('normal')
    self.splitter = QtWidgets.QSplitter()
    self.splitter.setStyleSheet(stylesheet_creation_function('qsplitter'))
    self.splitter.setOrientation(QtCore.Qt.Horizontal)
    self.splitter.setObjectName("splitter")
    self.variable_list = MyTreeWidget(self.splitter)
    self.variable_list.setEnabled(True)
    self.variable_list.setMinimumSize(QtCore.QSize(0, 0))
    self.variable_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.variable_list.setFont(font1)
    self.variable_list.setFocusPolicy(QtCore.Qt.NoFocus)
    self.variable_list.setStyleSheet(stylesheet_creation_function('qtreewidget'))
    self.variable_list.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.variable_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
    self.variable_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
    self.variable_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
    self.variable_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
    self.variable_list.setDefaultDropAction(QtCore.Qt.MoveAction)
    self.variable_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
    self.variable_list.setObjectName("variable_list")
    self.variable_list.headerItem().setText(0, "1")
    self.variable_list.header().setVisible(False)
    self.variable_widget = QtWidgets.QWidget(self.splitter)
    self.variable_widget.setObjectName("variable_widget")
    self.metadata_container = QtWidgets.QVBoxLayout(self.variable_widget)
    self.metadata_container.setContentsMargins(0, 0, 0, 0)
    self.metadata_container.setObjectName("metadata_container")
    self.variable_widget_container.addWidget(self.splitter)
    self.splitter.setSizes([270, 582])
    self.variable_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
    self.variable_list.customContextMenuRequested.connect(self.right_click_menu)
    self.variable_list.itemClicked.connect(lambda: nc_tree_var_reading(self))
    self.variable_list.itemClicked.connect(lambda: update_icons_state(self))
    self.variable_list.itemSelectionChanged.connect(lambda: clear_metadata_layout(self))
    self.variable_list.dropFile.connect(lambda path_object: tree_widget_move_actions(self, path_object))


def clear_metadata_layout(self):
    items = self.variable_list.selectedItems()
    if len(items) == 0:
        clear_layout(self.metadata_container)
        update_icons_state(self)


def add_netcdf_variable_metadata_widgets(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    icon2 = icon_creation_function('dimension_icon.svg')
    self.dataset_grid = QtWidgets.QGridLayout()
    self.dataset_grid.setContentsMargins(5, -1, -1, -1)
    self.dataset_grid.setVerticalSpacing(10)
    self.dataset_grid.setObjectName("dataset_grid")
    self.var_varname_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_varname_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_varname_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_varname_lb.setFont(font1)
    self.var_varname_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_varname_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_varname_lb.setObjectName("var_varname_lb")
    self.dataset_grid.addWidget(self.var_varname_lb, 1, 0, 1, 1)
    self.var_long_name_bt = PushButtonRight(self.variable_widget)
    self.var_long_name_bt.setEnabled(False)
    self.var_long_name_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.var_long_name_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.var_long_name_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.var_long_name_bt.setText("")
    self.var_long_name_bt.setIcon(icon1)
    self.var_long_name_bt.setIconSize(QtCore.QSize(23, 23))
    self.var_long_name_bt.setObjectName("var_long_name_bt")
    self.dataset_grid.addWidget(self.var_long_name_bt, 2, 2, 1, 1)
    self.var_dimensions_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_dimensions_ln.setEnabled(False)
    self.var_dimensions_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_dimensions_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_dimensions_ln.setFont(font2)
    self.var_dimensions_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_dimensions_ln.setText("")
    self.var_dimensions_ln.setFrame(False)
    self.var_dimensions_ln.setObjectName("var_dimensions_ln")
    self.dataset_grid.addWidget(self.var_dimensions_ln, 6, 1, 1, 1)
    self.var_dimension_bt = QtWidgets.QToolButton(self.variable_widget)
    self.var_dimension_bt.setEnabled(False)
    self.var_dimension_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.var_dimension_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.var_dimension_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.var_dimension_bt.setText("")
    self.var_dimension_bt.setIcon(icon2)
    self.var_dimension_bt.setIconSize(QtCore.QSize(23, 23))
    self.var_dimension_bt.setObjectName("var_dimension_bt")
    self.dataset_grid.addWidget(self.var_dimension_bt, 6, 2, 1, 1)
    self.var_long_name_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_long_name_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_long_name_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_long_name_lb.setFont(font1)
    self.var_long_name_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_long_name_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_long_name_lb.setObjectName("var_long_name_lb")
    self.dataset_grid.addWidget(self.var_long_name_lb, 2, 0, 1, 1)
    self.var_long_name_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_long_name_ln.setEnabled(False)
    self.var_long_name_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_long_name_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_long_name_ln.setFont(font2)
    self.var_long_name_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_long_name_ln.setText("")
    self.var_long_name_ln.setFrame(False)
    self.var_long_name_ln.setObjectName("var_long_name_ln")
    self.dataset_grid.addWidget(self.var_long_name_ln, 2, 1, 1, 1)
    self.var_fillvalue_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_fillvalue_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_fillvalue_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_fillvalue_lb.setFont(font1)
    self.var_fillvalue_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_fillvalue_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_fillvalue_lb.setObjectName("var_fillvalue_lb")
    self.dataset_grid.addWidget(self.var_fillvalue_lb, 5, 0, 1, 1)
    self.var_units_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_units_ln.setEnabled(False)
    self.var_units_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_units_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_units_ln.setFont(font2)
    self.var_units_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_units_ln.setText("")
    self.var_units_ln.setFrame(False)
    self.var_units_ln.setObjectName("var_units_ln")
    self.dataset_grid.addWidget(self.var_units_ln, 4, 1, 1, 1)
    self.var_egadsprocessor_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_egadsprocessor_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_egadsprocessor_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.var_egadsprocessor_lb.setFont(font1)
    self.var_egadsprocessor_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_egadsprocessor_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
    self.var_egadsprocessor_lb.setObjectName("var_egadsprocessor_lb")
    self.dataset_grid.addWidget(self.var_egadsprocessor_lb, 7, 0, 1, 1)
    self.var_varname_bt = PushButtonRight(self.variable_widget)
    self.var_varname_bt.setEnabled(False)
    self.var_varname_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.var_varname_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.var_varname_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.var_varname_bt.setText("")
    self.var_varname_bt.setIcon(icon1)
    self.var_varname_bt.setIconSize(QtCore.QSize(23, 23))
    self.var_varname_bt.setObjectName("var_varname_bt")
    self.dataset_grid.addWidget(self.var_varname_bt, 1, 2, 1, 1)
    self.var_Category_bt = PushButtonRight(self.variable_widget)
    self.var_Category_bt.setEnabled(False)
    self.var_Category_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.var_Category_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.var_Category_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.var_Category_bt.setText("")
    self.var_Category_bt.setIcon(icon1)
    self.var_Category_bt.setIconSize(QtCore.QSize(23, 23))
    self.var_Category_bt.setObjectName("var_Category_bt")
    self.dataset_grid.addWidget(self.var_Category_bt, 3, 2, 1, 1)
    self.var_dimensions_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_dimensions_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_dimensions_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_dimensions_lb.setFont(font1)
    self.var_dimensions_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_dimensions_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_dimensions_lb.setObjectName("var_dimensions_lb")
    self.dataset_grid.addWidget(self.var_dimensions_lb, 6, 0, 1, 1)
    self.var_varname_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_varname_ln.setEnabled(False)
    self.var_varname_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_varname_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_varname_ln.setFont(font2)
    self.var_varname_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_varname_ln.setText("")
    self.var_varname_ln.setFrame(False)
    self.var_varname_ln.setObjectName("var_varname_ln")
    self.dataset_grid.addWidget(self.var_varname_ln, 1, 1, 1, 1)
    self.var_Category_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_Category_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_Category_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_Category_lb.setFont(font1)
    self.var_Category_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_Category_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_Category_lb.setObjectName("var_Category_lb")
    self.dataset_grid.addWidget(self.var_Category_lb, 3, 0, 1, 1)
    self.var_egadsprocessor_ln = QtWidgets.QPlainTextEdit(self.variable_widget)
    self.var_egadsprocessor_ln.setEnabled(False)
    self.var_egadsprocessor_ln.setMinimumSize(QtCore.QSize(0, 50))
    self.var_egadsprocessor_ln.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.var_egadsprocessor_ln.setFont(font2)
    self.var_egadsprocessor_ln.setStyleSheet(stylesheet_creation_function('qplaintextedit'))
    self.var_egadsprocessor_ln.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.var_egadsprocessor_ln.setPlainText("")
    self.var_egadsprocessor_ln.setObjectName("var_egadsprocessor_ln")
    self.dataset_grid.addWidget(self.var_egadsprocessor_ln, 7, 1, 1, 1)
    self.var_fillvalue_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_fillvalue_ln.setEnabled(False)
    self.var_fillvalue_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_fillvalue_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_fillvalue_ln.setFont(font2)
    self.var_fillvalue_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_fillvalue_ln.setText("")
    self.var_fillvalue_ln.setFrame(False)
    self.var_fillvalue_ln.setObjectName("var_fillvalue_ln")
    self.dataset_grid.addWidget(self.var_fillvalue_ln, 5, 1, 1, 1)
    self.var_Category_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_Category_ln.setEnabled(False)
    self.var_Category_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_Category_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_Category_ln.setFont(font2)
    self.var_Category_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_Category_ln.setText("")
    self.var_Category_ln.setFrame(False)
    self.var_Category_ln.setObjectName("var_Category_ln")
    self.dataset_grid.addWidget(self.var_Category_ln, 3, 1, 1, 1)
    self.var_units_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_units_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_units_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_units_lb.setFont(font1)
    self.var_units_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_units_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_units_lb.setObjectName("var_units_lb")
    self.dataset_grid.addWidget(self.var_units_lb, 4, 0, 1, 1)
    self.var_objecttype_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_objecttype_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_objecttype_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_objecttype_lb.setFont(font1)
    self.var_objecttype_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_objecttype_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_objecttype_lb.setObjectName("var_objecttype_lb")
    self.dataset_grid.addWidget(self.var_objecttype_lb, 0, 0, 1, 1)
    self.var_objecttype_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_objecttype_ln.setEnabled(False)
    self.var_objecttype_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_objecttype_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_objecttype_ln.setFont(font2)
    self.var_objecttype_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_objecttype_ln.setText("")
    self.var_objecttype_ln.setFrame(False)
    self.var_objecttype_ln.setObjectName("var_objecttype_ln")
    self.dataset_grid.addWidget(self.var_objecttype_ln, 0, 1, 1, 1)
    self.metadata_container.addLayout(self.dataset_grid)
    self.metadata_container.setAlignment(QtCore.Qt.AlignTop)
    self.var_varname_lb.setText("Variable name:")
    self.var_long_name_lb.setText("Long name:")
    self.var_fillvalue_lb.setText("Fill value:")
    self.var_egadsprocessor_lb.setText("<html><head/><body><p>EGADS<br/>processors:</p></body></html>")
    self.var_dimensions_lb.setText("Dimensions:")
    self.var_Category_lb.setText("Category:")
    self.var_units_lb.setText("Units:")
    self.var_objecttype_lb.setText("Object type:")
    self.var_dimension_bt.clicked.connect(lambda: dimension_selection_window(self))
    var_buttons = self.variable_widget.findChildren(PushButtonRight)
    for widget in var_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_var(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_var(self, 'right'))


def add_netcdf_group_metadata_widgets(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    self.group_grid = QtWidgets.QGridLayout()
    self.group_grid.setContentsMargins(5, -1, -1, -1)
    self.group_grid.setVerticalSpacing(10)
    self.group_grid.setObjectName("group_grid")
    self.var_objecttype_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_objecttype_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_objecttype_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_objecttype_lb.setFont(font1)
    self.var_objecttype_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_objecttype_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_objecttype_lb.setObjectName("var_objecttype_lb")
    self.group_grid.addWidget(self.var_objecttype_lb, 0, 0, 1, 1)
    self.var_groupname_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_groupname_ln.setEnabled(False)
    self.var_groupname_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_groupname_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_groupname_ln.setFont(font2)
    self.var_groupname_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_groupname_ln.setText("")
    self.var_groupname_ln.setFrame(False)
    self.var_groupname_ln.setObjectName("var_groupname_ln")
    self.group_grid.addWidget(self.var_groupname_ln, 1, 1, 1, 1)
    self.var_objecttype_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_objecttype_ln.setEnabled(False)
    self.var_objecttype_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_objecttype_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_objecttype_ln.setFont(font2)
    self.var_objecttype_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.var_objecttype_ln.setText("")
    self.var_objecttype_ln.setFrame(False)
    self.var_objecttype_ln.setObjectName("var_objecttype_ln")
    self.group_grid.addWidget(self.var_objecttype_ln, 0, 1, 1, 1)
    self.var_groupname_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_groupname_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_groupname_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_groupname_lb.setFont(font1)
    self.var_groupname_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.var_groupname_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_groupname_lb.setObjectName("var_groupname_lb")
    self.group_grid.addWidget(self.var_groupname_lb, 1, 0, 1, 1)
    self.var_groupname_bt = PushButtonRight(self.variable_widget)
    self.var_groupname_bt.setEnabled(False)
    self.var_groupname_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.var_groupname_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.var_groupname_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.var_groupname_bt.setText("")
    self.var_groupname_bt.setIcon(icon1)
    self.var_groupname_bt.setIconSize(QtCore.QSize(23, 23))
    self.var_groupname_bt.setObjectName("var_groupname_bt")
    self.group_grid.addWidget(self.var_groupname_bt, 1, 2, 1, 1)
    self.metadata_container.addLayout(self.group_grid)
    self.metadata_container.setAlignment(QtCore.Qt.AlignTop)
    self.var_objecttype_lb.setText("Object type:")
    self.var_groupname_lb.setText("Group name:")
    var_buttons = self.variable_widget.findChildren(PushButtonRight)
    for widget in var_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_var(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_var(self, 'right'))


def update_nc_global_attribute_gui(self):
    logging.debug('gui - gui_netcdf_functions.py - update_nc_global_attribute_gui')
    read_set_attribute_gui(self.glo_title_ln, 'title', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_institution_ln, 'institution', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_source_ln, 'source', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_project_ln, 'project', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_history_ln, 'history', self.list_of_global_attributes)


def update_nc_variable_attribute_gui(self):
    logging.debug('gui - gui_netcdf_functions.py - update_nc_variable_attribute_gui')
    path, var = full_path_name_from_treewidget(self.variable_list)
    try:
        sublist = self.list_of_variables_and_attributes[path]
    except KeyError:
        sublist = self.list_of_variables_and_attributes[path[1:]]
    dimensions_str = ''
    if isinstance(sublist[0], EgadsData):
        self.var_dimensions_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
        self.var_dimensions_lb.setToolTip('')
        if sublist[2]:
            read_set_attribute_gui(self.var_objecttype_ln, 'Dimension')
        else:
            read_set_attribute_gui(self.var_objecttype_ln, 'Dataset')
        read_set_attribute_gui(self.var_varname_ln, var)
        read_set_attribute_gui(self.var_long_name_ln, 'long_name', sublist[0].metadata)
        read_set_attribute_gui(self.var_units_ln, 'units', sublist[0].metadata)
        read_set_attribute_gui(self.var_Category_ln, 'Category', sublist[0].metadata)
        read_set_attribute_gui(self.var_egadsprocessor_ln, 'Processor', sublist[0].metadata)
        read_set_attribute_gui(self.var_fillvalue_ln, '_FillValue', sublist[0].metadata)
        if not self.var_fillvalue_ln.text():
            read_set_attribute_gui(self.var_fillvalue_ln, 'missing_value', sublist[0].metadata)
        if sublist[1] is not None:
            no_dim = False
            same_folder = True
            for key, value in sublist[1].items():
                if 'no dimension' in key:
                    no_dim = True
                    dimensions_str = dimensions_str + str(value) + ' (no dimension), '
                else:
                    dimensions_str = dimensions_str + str(value) + ' (' + os.path.basename(key) + '), '
                    if os.path.dirname(path) != os.path.dirname(key):
                        same_folder = False
            if no_dim or not same_folder:
                self.var_dimensions_lb.setStyleSheet(stylesheet_creation_function('qlabel_warning'))
                if no_dim:
                    self.var_dimensions_lb.setToolTip('One or more dimensions are missing')
                if not same_folder:
                    self.var_dimensions_lb.setToolTip('One or more dimensions are not from the same folder')
        else:
            if sublist[2]:
                dimensions_str = str(sublist[0].shape[0]) + ' (' + os.path.basename(path) + '), '
            else:
                self.var_dimensions_lb.setStyleSheet(stylesheet_creation_function('qlabel_warning'))
                self.var_dimensions_lb.setToolTip('This variable has no dimension')
                for value in sublist[0].shape:
                    dimensions_str = dimensions_str + str(value) + ', '
        read_set_attribute_gui(self.var_dimensions_ln, dimensions_str[:-2])
    else:
        read_set_attribute_gui(self.var_objecttype_ln, 'Group')
        read_set_attribute_gui(self.var_groupname_ln, var)


def populate_netcdf_tree_widget(self):
    populate_tree_widget(self.variable_list, self.list_of_variables_and_attributes)


def dimension_selection_window(self):
    is_dim = False
    path, _ = full_path_name_from_treewidget(self.variable_list)
    var = self.list_of_variables_and_attributes[path]
    dim_list = {var_name: var_dict[0].shape[0] for var_name, var_dict in self.list_of_variables_and_attributes.items()
                if var_dict[2]}
    if var[2]:
        is_dim = True
    selection_window = MyDimensionSelection(dim_list, var, path)
    selection_window.exec_()
    if not selection_window.cancel:
        if is_dim and not selection_window.variable[2]:
            for var_name, var_dict in self.list_of_variables_and_attributes.items():
                dim_dict = var_dict[1]
                if dim_dict is not None:
                    if path in dim_dict:
                        if len(dim_dict) == 1:
                            var_dict[1] = None

        update_tree_widget(self.variable_list, self.list_of_variables_and_attributes)
        update_nc_variable_attribute_gui(self)
        self.modified = True
        self.make_window_title()
        self.start_status_bar_msg_thread('Dimensions have been modified...')


def tree_widget_move_actions(self, path_object):
    move_object_in_variable_dict(self, path_object)
    update_tree_widget(self.variable_list, self.list_of_variables_and_attributes)
    self.modified = True
    self.make_window_title()
    self.start_status_bar_msg_thread('Variables and/or folders have been moved...')
