import logging
from PyQt5 import QtWidgets, QtCore
from functions.utils import (font_creation_function, clear_layout, icon_creation_function, stylesheet_creation_function,
                             full_path_name_from_treewidget)
from functions.gui_functions.gui_widgets import PushButtonRight
from functions.gui_functions.gui_global_functions import (update_icons_state, read_set_attribute_gui,
                                                          update_edit_icon_state, modify_attribute_gui_global,
                                                          modify_attribute_gui_var)


def nasaames_gui_initialization(self):
    logging.debug('gui - gui_nasaames_functions.py - nasaames_gui_initialization')
    self.gridLayout.addWidget(self.tab_view, 0, 0, 1, 1)
    self.tab_view.setEnabled(True)
    self.tab_view.setVisible(True)
    self.tab_view.currentChanged.connect(lambda: update_icons_state(self))
    add_nasaames_global_tab(self)
    add_nasaames_variable_tab(self)


def add_nasaames_global_tab(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    self.global_widget = QtWidgets.QWidget()
    self.global_widget.setObjectName("global_widget")
    self.global_grid = QtWidgets.QGridLayout()
    self.global_grid.setVerticalSpacing(15)
    self.global_grid.setObjectName("global_grid")
    self.glo_MNAME_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_MNAME_ln.setEnabled(False)
    self.glo_MNAME_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_MNAME_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_MNAME_ln.setFont(font2)
    self.glo_MNAME_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_MNAME_ln.setText("")
    self.glo_MNAME_ln.setFrame(False)
    self.glo_MNAME_ln.setObjectName("glo_MNAME_ln")
    self.global_grid.addWidget(self.glo_MNAME_ln, 0, 1, 1, 1)
    self.glo_MNAME_bt = PushButtonRight(self.global_widget)
    self.glo_MNAME_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_MNAME_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_MNAME_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_MNAME_bt.setText("")
    self.glo_MNAME_bt.setIcon(icon1)
    self.glo_MNAME_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_MNAME_bt.setObjectName("glo_MNAME_bt")
    self.global_grid.addWidget(self.glo_MNAME_bt, 0, 2, 1, 1)
    self.global_grid.addItem(QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed,
                                                   QtWidgets.QSizePolicy.Minimum), 0, 3, 2, 1)
    self.glo_MNAME_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_MNAME_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_MNAME_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_MNAME_lb.setFont(font1)
    self.glo_MNAME_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_MNAME_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_MNAME_lb.setObjectName("glo_MNAME_lb")
    self.global_grid.addWidget(self.glo_MNAME_lb, 0, 0, 1, 1)
    self.glo_SNAME_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_SNAME_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_SNAME_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_SNAME_lb.setFont(font1)
    self.glo_SNAME_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_SNAME_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_SNAME_lb.setObjectName("glo_SNAME_lb")
    self.global_grid.addWidget(self.glo_SNAME_lb, 0, 4, 1, 1)
    self.glo_SNAME_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_SNAME_ln.setEnabled(False)
    self.glo_SNAME_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_SNAME_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_SNAME_ln.setFont(font2)
    self.glo_SNAME_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_SNAME_ln.setText("")
    self.glo_SNAME_ln.setFrame(False)
    self.glo_SNAME_ln.setObjectName("glo_SNAME_ln")
    self.global_grid.addWidget(self.glo_SNAME_ln, 0, 5, 1, 1)
    self.glo_SNAME_bt = PushButtonRight(self.global_widget)
    self.glo_SNAME_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_SNAME_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_SNAME_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_SNAME_bt.setText("")
    self.glo_SNAME_bt.setIcon(icon1)
    self.glo_SNAME_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_SNAME_bt.setObjectName("glo_SNAME_bt")
    self.global_grid.addWidget(self.glo_SNAME_bt, 0, 6, 1, 1)
    self.glo_ORG_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_ORG_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_ORG_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_ORG_lb.setFont(font1)
    self.glo_ORG_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_ORG_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_ORG_lb.setObjectName("glo_ORG_lb")
    self.global_grid.addWidget(self.glo_ORG_lb, 1, 0, 1, 1)
    self.glo_ORG_bt = PushButtonRight(self.global_widget)
    self.glo_ORG_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_ORG_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_ORG_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_ORG_bt.setText("")
    self.glo_ORG_bt.setIcon(icon1)
    self.glo_ORG_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_ORG_bt.setObjectName("glo_ORG_bt")
    self.global_grid.addWidget(self.glo_ORG_bt, 1, 2, 1, 1)
    self.glo_ONAME_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_ONAME_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_ONAME_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_ONAME_lb.setFont(font1)
    self.glo_ONAME_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_ONAME_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.glo_ONAME_lb.setObjectName("glo_ONAME_lb")
    self.global_grid.addWidget(self.glo_ONAME_lb, 1, 4, 1, 1)
    self.glo_ORG_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_ORG_ln.setEnabled(False)
    self.glo_ORG_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_ORG_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_ORG_ln.setFont(font2)
    self.glo_ORG_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_ORG_ln.setText("")
    self.glo_ORG_ln.setFrame(False)
    self.glo_ORG_ln.setObjectName("glo_ORG_ln")
    self.global_grid.addWidget(self.glo_ORG_ln, 1, 1, 1, 1)
    self.glo_ONAME_bt = PushButtonRight(self.global_widget)
    self.glo_ONAME_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_ONAME_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_ONAME_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_ONAME_bt.setText("")
    self.glo_ONAME_bt.setIcon(icon1)
    self.glo_ONAME_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_ONAME_bt.setObjectName("glo_ONAME_bt")
    self.global_grid.addWidget(self.glo_ONAME_bt, 1, 6, 1, 1)
    self.glo_ONAME_ln = QtWidgets.QLineEdit(self.global_widget)
    self.glo_ONAME_ln.setEnabled(False)
    self.glo_ONAME_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_ONAME_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.glo_ONAME_ln.setFont(font2)
    self.glo_ONAME_ln.setStyleSheet(stylesheet_creation_function('qlineedit'))
    self.glo_ONAME_ln.setText("")
    self.glo_ONAME_ln.setFrame(False)
    self.glo_ONAME_ln.setObjectName("glo_ONAME_ln")
    self.global_grid.addWidget(self.glo_ONAME_ln, 1, 5, 1, 1)
    self.glo_NCOM_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_NCOM_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_NCOM_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.glo_NCOM_lb.setFont(font1)
    self.glo_NCOM_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_NCOM_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
    self.glo_NCOM_lb.setObjectName("glo_NCOM_lb")
    self.global_grid.addWidget(self.glo_NCOM_lb, 2, 0, 1, 1)
    self.glo_NCOM_ln = QtWidgets.QPlainTextEdit(self.global_widget)
    self.glo_NCOM_ln.setEnabled(False)
    self.glo_NCOM_ln.setMinimumSize(QtCore.QSize(0, 100))
    self.glo_NCOM_ln.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.glo_NCOM_ln.setFont(font2)
    self.glo_NCOM_ln.setStyleSheet(stylesheet_creation_function('qplaintextedit'))
    self.glo_NCOM_ln.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.glo_NCOM_ln.setPlainText("")
    self.glo_NCOM_ln.setObjectName("glo_NCOM_ln")
    self.global_grid.addWidget(self.glo_NCOM_ln, 2, 1, 1, 5)
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.glo_NCOM_bt = PushButtonRight(self.global_widget)
    self.glo_NCOM_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_NCOM_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_NCOM_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_NCOM_bt.setText("")
    self.glo_NCOM_bt.setIcon(icon1)
    self.glo_NCOM_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_NCOM_bt.setObjectName("glo_NCOM_bt")
    self.verticalLayout.addWidget(self.glo_NCOM_bt)
    self.verticalLayout.addItem(QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                      QtWidgets.QSizePolicy.Expanding))
    self.global_grid.addLayout(self.verticalLayout, 2, 6, 1, 1)
    self.glo_SCOM_lb = QtWidgets.QLabel(self.global_widget)
    self.glo_SCOM_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.glo_SCOM_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.glo_SCOM_lb.setFont(font1)
    self.glo_SCOM_lb.setStyleSheet(stylesheet_creation_function('qlabel'))
    self.glo_SCOM_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
    self.glo_SCOM_lb.setObjectName("glo_SCOM_lb")
    self.global_grid.addWidget(self.glo_SCOM_lb, 3, 0, 1, 1)
    self.glo_SCOM_ln = QtWidgets.QPlainTextEdit(self.global_widget)
    self.glo_SCOM_ln.setEnabled(False)
    self.glo_SCOM_ln.setMinimumSize(QtCore.QSize(0, 100))
    self.glo_SCOM_ln.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.glo_SCOM_ln.setFont(font2)
    self.glo_SCOM_ln.setStyleSheet(stylesheet_creation_function('qplaintextedit'))
    self.glo_SCOM_ln.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.glo_SCOM_ln.setPlainText("")
    self.glo_SCOM_ln.setObjectName("glo_SCOM_ln")
    self.global_grid.addWidget(self.glo_SCOM_ln, 3, 1, 1, 5)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.glo_SCOM_bt = PushButtonRight(self.global_widget)
    self.glo_SCOM_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.glo_SCOM_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.glo_SCOM_bt.setStyleSheet(stylesheet_creation_function('qtoolbutton'))
    self.glo_SCOM_bt.setText("")
    self.glo_SCOM_bt.setIcon(icon1)
    self.glo_SCOM_bt.setIconSize(QtCore.QSize(23, 23))
    self.glo_SCOM_bt.setObjectName("glo_SCOM_bt")
    self.verticalLayout_2.addWidget(self.glo_SCOM_bt)
    self.verticalLayout_2.addItem(QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                        QtWidgets.QSizePolicy.Expanding))
    self.global_grid.addLayout(self.verticalLayout_2, 3, 6, 1, 1)
    self.global_container.addLayout(self.global_grid)
    self.global_container.setAlignment(QtCore.Qt.AlignTop)
    self.glo_MNAME_lb.setText("Title - MNAME:")
    self.glo_SNAME_lb.setText("Source - SNAME:")
    self.glo_ORG_lb.setText("Institution - ORG:")
    self.glo_ONAME_lb.setText("Author - ONAME:")
    self.glo_NCOM_lb.setText("<html><head/><body><p>Normal comments<br>- NCOM:</p></body></html>")
    self.glo_SCOM_lb.setText("<html><head/><body><p>Special comments<br>- SCOM:</p></body></html>")
    glo_buttons = self.tab.findChildren(PushButtonRight)
    for widget in glo_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_global(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_global(self, 'right'))


def add_nasaames_variable_tab(self):
    font1 = font_creation_function('normal')
    self.splitter = QtWidgets.QSplitter()
    self.splitter.setStyleSheet(stylesheet_creation_function('qsplitter'))
    self.splitter.setOrientation(QtCore.Qt.Horizontal)
    self.splitter.setObjectName("splitter")
    self.variable_list = QtWidgets.QTreeWidget(self.splitter)
    self.variable_list.setEnabled(True)
    self.variable_list.setMinimumSize(QtCore.QSize(0, 0))
    self.variable_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.variable_list.setFont(font1)
    self.variable_list.setFocusPolicy(QtCore.Qt.NoFocus)
    self.variable_list.setStyleSheet(stylesheet_creation_function('qtreewidget'))
    self.variable_list.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.variable_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
    self.variable_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
    self.variable_list.setObjectName("variable_list")
    self.variable_list.headerItem().setText(0, "1")
    self.variable_list.header().setVisible(False)
    self.variable_widget = QtWidgets.QWidget(self.splitter)
    self.variable_widget.setObjectName("variable_widget")
    self.metadata_container = QtWidgets.QVBoxLayout(self.variable_widget)
    self.metadata_container.setContentsMargins(0, 0, 0, 0)
    self.metadata_container.setObjectName("metadata_container")
    self.variable_widget_container.addWidget(self.splitter)
    self.splitter.setSizes([270, 582])
    self.variable_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
    self.variable_list.customContextMenuRequested.connect(self.right_click_menu)
    self.variable_list.itemClicked.connect(lambda: na_tree_var_reading(self))
    self.variable_list.itemClicked.connect(lambda: update_icons_state(self))
    # self.variable_list.dropFile.connect(lambda path_object: move_object_in_variable_dict(self, path_object))


def update_na_global_attribute_gui(self):
    logging.debug('gui - gui_netcdf_functions.py - update_na_global_attribute_gui')
    read_set_attribute_gui(self.glo_MNAME_ln, 'MNAME', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_ORG_ln, 'ORG', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_SNAME_ln, 'SNAME', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_ONAME_ln, 'ONAME', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_NCOM_ln, 'NCOM', self.list_of_global_attributes)
    read_set_attribute_gui(self.glo_SCOM_ln, 'SCOM', self.list_of_global_attributes)


def populate_na_tree_widget(self):
    self.variable_list.clear()
    for key in sorted(list(self.list_of_variables_and_attributes.keys())):
        widget = QtWidgets.QTreeWidgetItem()
        widget.setText(0, key[1:])
        widget.setToolTip(0, 'dataset: ' + key[1:])
        self.variable_list.addTopLevelItem(widget)


def na_tree_var_reading(self):
    if len(self.variable_list.selectedItems()) == 1:
        clear_layout(self.metadata_container)
        add_na_variable_metadata_widgets(self)
        update_na_variable_attribute_gui(self)
        update_edit_icon_state(self)
    else:
        clear_layout(self.metadata_container)


def add_na_variable_metadata_widgets(self):
    font1 = font_creation_function('normal')
    font2 = font_creation_function('small')
    icon1 = icon_creation_function('edit_icon.svg')
    self.dataset_grid = QtWidgets.QGridLayout()
    self.dataset_grid.setContentsMargins(5, -1, -1, -1)
    self.dataset_grid.setVerticalSpacing(10)
    self.dataset_grid.setObjectName("dataset_grid")
    self.var_units_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_units_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_units_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_units_lb.setFont(font1)
    self.var_units_lb.setStyleSheet(stylesheet_creation_function("qlabel"))
    self.var_units_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_units_lb.setObjectName("var_units_lb")
    self.dataset_grid.addWidget(self.var_units_lb, 1, 0, 1, 1)
    self.var_egadsprocessor_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_egadsprocessor_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_egadsprocessor_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.var_egadsprocessor_lb.setFont(font1)
    self.var_egadsprocessor_lb.setStyleSheet(stylesheet_creation_function("qlabel"))
    self.var_egadsprocessor_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
    self.var_egadsprocessor_lb.setObjectName("var_egadsprocessor_lb")
    self.dataset_grid.addWidget(self.var_egadsprocessor_lb, 4, 0, 1, 1)
    self.var_dimensions_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_dimensions_ln.setEnabled(False)
    self.var_dimensions_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_dimensions_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_dimensions_ln.setFont(font2)
    self.var_dimensions_ln.setStyleSheet(stylesheet_creation_function("qlineedit"))
    self.var_dimensions_ln.setText("")
    self.var_dimensions_ln.setFrame(False)
    self.var_dimensions_ln.setObjectName("var_dimensions_ln")
    self.dataset_grid.addWidget(self.var_dimensions_ln, 3, 1, 1, 1)
    self.var_varname_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_varname_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_varname_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_varname_lb.setFont(font1)
    self.var_varname_lb.setStyleSheet(stylesheet_creation_function("qlabel"))
    self.var_varname_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_varname_lb.setObjectName("var_varname_lb")
    self.dataset_grid.addWidget(self.var_varname_lb, 0, 0, 1, 1)
    self.var_fillvalue_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_fillvalue_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_fillvalue_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_fillvalue_lb.setFont(font1)
    self.var_fillvalue_lb.setStyleSheet(stylesheet_creation_function("qlabel"))
    self.var_fillvalue_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_fillvalue_lb.setObjectName("var_fillvalue_lb")
    self.dataset_grid.addWidget(self.var_fillvalue_lb, 2, 0, 1, 1)
    self.var_egadsprocessor_ln = QtWidgets.QPlainTextEdit(self.variable_widget)
    self.var_egadsprocessor_ln.setEnabled(False)
    self.var_egadsprocessor_ln.setMinimumSize(QtCore.QSize(0, 100))
    self.var_egadsprocessor_ln.setMaximumSize(QtCore.QSize(16777215, 100))
    self.var_egadsprocessor_ln.setFont(font2)
    self.var_egadsprocessor_ln.setStyleSheet(stylesheet_creation_function("qplaintextedit"))
    self.var_egadsprocessor_ln.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.var_egadsprocessor_ln.setPlainText("")
    self.var_egadsprocessor_ln.setObjectName("var_egadsprocessor_ln")
    self.dataset_grid.addWidget(self.var_egadsprocessor_ln, 4, 1, 1, 1)
    self.var_units_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_units_ln.setEnabled(False)
    self.var_units_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_units_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_units_ln.setFont(font2)
    self.var_units_ln.setStyleSheet(stylesheet_creation_function("qlineedit"))
    self.var_units_ln.setText("")
    self.var_units_ln.setFrame(False)
    self.var_units_ln.setObjectName("var_units_ln")
    self.dataset_grid.addWidget(self.var_units_ln, 1, 1, 1, 1)
    self.var_varname_bt = PushButtonRight(self.variable_widget)
    self.var_varname_bt.setEnabled(False)
    self.var_varname_bt.setMinimumSize(QtCore.QSize(27, 27))
    self.var_varname_bt.setMaximumSize(QtCore.QSize(27, 27))
    self.var_varname_bt.setStyleSheet(stylesheet_creation_function("qtoolbutton"))
    self.var_varname_bt.setText("")
    self.var_varname_bt.setIcon(icon1)
    self.var_varname_bt.setIconSize(QtCore.QSize(23, 23))
    self.var_varname_bt.setObjectName("var_varname_bt")
    self.dataset_grid.addWidget(self.var_varname_bt, 0, 2, 1, 1)
    self.var_dimensions_lb = QtWidgets.QLabel(self.variable_widget)
    self.var_dimensions_lb.setMinimumSize(QtCore.QSize(0, 27))
    self.var_dimensions_lb.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_dimensions_lb.setFont(font1)
    self.var_dimensions_lb.setStyleSheet(stylesheet_creation_function("qlabel"))
    self.var_dimensions_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    self.var_dimensions_lb.setObjectName("var_dimensions_lb")
    self.dataset_grid.addWidget(self.var_dimensions_lb, 3, 0, 1, 1)
    self.var_varname_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_varname_ln.setEnabled(False)
    self.var_varname_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_varname_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_varname_ln.setFont(font2)
    self.var_varname_ln.setStyleSheet(stylesheet_creation_function("qlineedit"))
    self.var_varname_ln.setText("")
    self.var_varname_ln.setFrame(False)
    self.var_varname_ln.setObjectName("var_varname_ln")
    self.dataset_grid.addWidget(self.var_varname_ln, 0, 1, 1, 1)
    self.var_fillvalue_ln = QtWidgets.QLineEdit(self.variable_widget)
    self.var_fillvalue_ln.setEnabled(False)
    self.var_fillvalue_ln.setMinimumSize(QtCore.QSize(0, 27))
    self.var_fillvalue_ln.setMaximumSize(QtCore.QSize(16777215, 27))
    self.var_fillvalue_ln.setFont(font2)
    self.var_fillvalue_ln.setStyleSheet(stylesheet_creation_function("qlineedit"))
    self.var_fillvalue_ln.setText("")
    self.var_fillvalue_ln.setFrame(False)
    self.var_fillvalue_ln.setObjectName("var_fillvalue_ln")
    self.dataset_grid.addWidget(self.var_fillvalue_ln, 2, 1, 1, 1)
    self.metadata_container.addLayout(self.dataset_grid)
    self.metadata_container.addItem(QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                          QtWidgets.QSizePolicy.Expanding))
    self.metadata_container.setAlignment(QtCore.Qt.AlignTop)
    self.var_units_lb.setText("Units:")
    self.var_egadsprocessor_lb.setText("<html><head/><body><p>EGADS<br/>processors:</p></body></html>")
    self.var_varname_lb.setText("Variable name:")
    self.var_fillvalue_lb.setText("Fill value:")
    self.var_dimensions_lb.setText("Dimensions:")
    var_buttons = self.variable_widget.findChildren(PushButtonRight)
    for widget in var_buttons:
        widget.clicked.connect(lambda: modify_attribute_gui_var(self, 'left'))
        widget.rightClick.connect(lambda: modify_attribute_gui_var(self, 'right'))


def update_na_variable_attribute_gui(self):
    logging.debug('gui - gui_netcdf_functions.py - update_na_variable_attribute_gui')
    path, var = full_path_name_from_treewidget(self.variable_list)
    try:
        sublist = self.list_of_variables_and_attributes[path]
    except KeyError:
        sublist = self.list_of_variables_and_attributes[path[1:]]
    dimensions_str = ''
    read_set_attribute_gui(self.var_varname_ln, var)
    read_set_attribute_gui(self.var_units_ln, 'units', sublist[0].metadata)
    read_set_attribute_gui(self.var_egadsprocessor_ln, 'Processor', sublist[0].metadata)
    read_set_attribute_gui(self.var_fillvalue_ln, '_FillValue', sublist[0].metadata)
    if not self.var_fillvalue_ln.text():
        read_set_attribute_gui(self.var_fillvalue_ln, 'missing_value', sublist[0].metadata)
    for key, value in sublist[1].items():
        dimensions_str = dimensions_str + str(value) + ' (' + key + '), '
    read_set_attribute_gui(self.var_dimensions_ln, dimensions_str[:-2])
